In [2]:
import streamlit as st
import pandas as pd

In [3]:
 st.write("""
# My first app
Hello *world!*
""")

2024-01-19 16:19:45.370
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\Admin\anaconda3\lib\site-packages\ipykernel_launcher.py [ARGUMENTS]

In [5]:
df = pd.read_csv("Medicalpremium.csv")
st.line_chart(df)

DeltaGenerator()

In [6]:
df

,Age,Diabetes,BloodPressureProblems,AnyTransplants,AnyChronicDiseases,Height,Weight,KnownAllergies,HistoryOfCancerInFamily,NumberOfMajorSurgeries,PremiumPrice
0,45,0,0,0,0,155,57,0,0,0,25000
1,60,1,0,0,0,180,73,0,0,0,29000
2,36,1,1,0,0,158,59,0,0,1,23000
3,52,1,1,0,1,183,93,0,0,2,28000
4,38,0,0,0,1,166,88,0,0,1,23000
...,...,...,...,...,...,...,...,...,...,...,...
981,18,0,0,0,0,169,67,0,0,0,15000
982,64,1,1,0,0,153,70,0,0,3,28000
983,56,0,1,0,0,155,71,0,0,1,29000
984,47,1,1,0,0,158,73,1,0,1,39000
985,21,0,0,0,0,158,75,1,0,1,15000